### ISSUE TITLE
admin/plugin_settings/oembed

### ISSUE THREAD

**Issue by oranyero** [ColdTrick/oembed#1]
Error Fatal
Class 'Embed\Http\Url' not found

Log at time 2020-03-21T21:42:41+00:00 may have more data.

**Comment by jeabakker** [comment]
It sounds like you didn't get the composer dependencies.

How did you install
- git clone / git download
- download from the community site
- the non source zip from the releases page

**Comment by oranyero** [comment]
Thx!
